name: walletconnect_flutter_dapp
description: A dApp showing how to use WalletConnect v2 with Flutter

publish_to: "none"

version: 3.2.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_toast: ^3.1.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  web3modal_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/abis/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
