name: web3modal_flutter
description: The Web3Modal for WalletConnect built using Flutter.
version: 1.2.1
repository: https://github.com/WalletConnect/WalletConnectFlutterV2

environment:
  sdk: '>=2.17.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  walletconnect_flutter_v2: ^2.0.6
  flutter_svg: ^2.0.6
  qr_flutter: ^4.1.0
  json_annotation: ^4.8.1
  url_launcher: ^6.1.11
  universal_io: ^2.2.0
  w_common: ^3.0.0
  logger: ^1.4.0
  http: ^0.13.6
  freezed_annotation: ^2.2.0
  flex_color_picker: ^3.2.2
  mockito: ^5.4.2
  walletconnect_modal_flutter: ^1.1.6
  web3dart: ^2.6.1
  hexagon: ^0.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  freezed: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/

