name: web3modal_flutter
description: "WalletConnect Web3Modal: Simple, intuitive wallet login. With this drop-in UI SDK, enable any wallet's users to seamlessly log in to your app and enjoy a unified experience"
version: 3.0.1
repository: https://github.com/WalletConnect/Web3ModalFlutter

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  appcheck: ^1.0.6
  cached_network_image: ^3.3.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.8.1
  event: ^2.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mockito: ^5.4.2
  qr_flutter_wc: ^0.0.3
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  universal_io: ^2.2.0
  url_launcher: ^6.1.11
  walletconnect_flutter_v2: ^2.1.10
  web3dart: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test: 
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  lints: ^2.1.1
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dark/
    - assets/light/
    - assets/icons/
    - assets/help/
    - assets/png/
    - assets/png/2.0x/
    - assets/png/3.0x/

